### PR TITLE
Added an alias for parse as parce - a common misspelling

### PR DESCRIPTION
**Pull request by JayTurnr**
I, and I am sure several others, have this horrible habit of not being able to spell parse correctly.

### CODE REVIEW

**Comment by kennethreitz** [comment]
Not happening — but thank you.

**Comment by JayTurnr** [comment]
Oh shame, any reason why?

**Comment by kennethreitz** [comment]
That is not how you design libraries.

**Comment by kennethreitz** [comment]
I could write a lengthy essay explaining, but I'd rather just leave it at "it is not proper". :)

**Pull request closed without merging**
