### PR TITLE
Interactive demo

### PR DESCRIPTION
**Pull request by martinzugnoni**
Hi guys, following our discussion here https://github.com/kennethreitz/maya/issues/167, this PR adds a link to the DEMO Notebook running on https://notebooks.ai/.

_** Note that the link won't work until this PR is merged, because it looks for a `DEMO.ipynb` file which is still not present in kennethreitz's repo. If you want to see how it will look like, you can take a look at it [here](https://notebooks.ai/demo/gh/martinzugnoni/maya)_

Anything here can be changed. Post your thoughts and we can iterate from there.

### CODE REVIEW

**Comment by timofurrer** [comment]
Is it possible to move the demo files into a separate directory instead of having them in the root of the project?

**Comment by martinzugnoni** [comment]
Hmm I think it's not, Timo. In order to keep it as simple as possible the notebooks.ai guys rely on some conventions and I guess the DEMO name and location is one of them.
Is that a big issue?

**Comment by timofurrer** [comment]
> Is that a big issue?

Well, I just like things to be sorted - no big deal though.

**Comment by timofurrer** [comment]
Thanks 🎉

**Pull request merged**
