### PR TITLE
comparision operation support and subtraction of MayaDT object

### PR DESCRIPTION
**Pull request by moin18**
Allow comparison operations and subtraction of MayaDT objects

### CODE REVIEW

**Comment by kennethreitz** [comment]
i'm going to have to spend some time with this

**Comment by kennethreitz** [comment]
can you add some tests?

**Comment by kennethreitz** [comment]
ah, you did!

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by moin18** [comment]
I think it was one of the very critical missing piece. It is something we perform on day to day basis with datetime objects

**Pull request merged**
