### PR TITLE
Parsing an ISO8601 duration for an interval

### PR DESCRIPTION
**Pull request by matmunn**
Will only currently work for calculating a duration after a start date - I need to come up with a good way of calculating the end date first so that a duration could be used as a start time.

### CODE REVIEW

**Comment by timofurrer** [comment]
Awesome, thanks!

**Comment by sdispater** [comment]
@matmunn You might want to wait for the release of pendulum 2.0 which will support ISO8601 Interval and durations parsing, see (https://github.com/sdispater/pendulum/blob/2.0/docs/docs/parsing.md).

It will have the advantage of being fast since it will use the c extensions (https://github.com/sdispater/pendulum/blob/2.0/pendulum/parsing/_iso8601.c) when available and it will also support partial units (which are part of the spec).

**Comment by matmunn** [comment]
@sdispater awesome, do you have a rough date for release? I'd be happy to switch this out in favour of pendulum when v2 is available available.

**Comment by sdispater** [comment]
@matmunn I expect a release in April, hopefully in the first half.

I still have Python 2.7 compatibility to tackle but after that it should be good.

I will keep you posted.

**Pull request merged**
