### PR TITLE
Remove probably obsolete requirement for ruamel.yaml

### PR DESCRIPTION
**Pull request by vlcinsky**
See issue #134

### CODE REVIEW

**Comment by timofurrer** [comment]
@kennethreitz why are we using `ruamel.yaml` ? I've noticed that `dateparser` is using `ruamel.yaml` but when is this warning raised which we are ignoring?

**Comment by asadurski** [comment]
@timofurrer `dateparser` dropped dependency on `ruamel.yaml` in recent version 0.7.0 (https://github.com/scrapinghub/dateparser/pull/374).

**Comment by timofurrer** [comment]
@asadurski Thanks for the input! I guess we removed it then, too :tada:

**Comment by timofurrer** [comment]
@vlcinsky Can you pin the `dateparser` to versions greater than 0.7.0 ?

**Comment by vlcinsky** [comment]
@timofurrer dateparser pinned as requested.

**Comment by timofurrer** [comment]
Great, thanks! I'm going to merge this :tada:

**Comment by benswift** [comment]
Awesome - this has been bugging me for a while as well. Any idea when the sans-ruamel.yaml version will be released to PyPI?

**Comment by benswift** [comment]
ping! any word on a new release?

**Comment by timofurrer** [comment]
I've just released v0.4.1 which you can use :tada:

**Comment by benswift** [comment]
many thanks

**Pull request merged**
