### PR TITLE
add compatibility for Python3

### PR DESCRIPTION
**Pull request by Tafkas**
Added a compat.py (inspired by the one from twisted)

### CODE REVIEW

**Comment by kennethreitz** [comment]
now, we need to make `maya` a package instead of a single `.py` file. are you up to that task?

**Comment by kennethreitz** [comment]
btw, thanks so much!

**Comment by Tafkas** [comment]
This is super odd. The tests "sometimes" fail locally on my machine giving the following error:

```
E       assert [<MayaInterva...7994.322344>>] == [<MayaInterval...7994.322344>>]
E         At index 0 diff: <MayaInterval start=<MayaDT epoch=1495744194.322344> end=<MayaDT epoch=1495817994.322344>> != <MayaInterval start=<MayaDT epoch=1495744194.3223438> end=<MayaDT epoch=1495817994.322344>>
```
The problematic part is, that start epoch seems to be different at the 8th digit:

1495744194.322344 <> 1495744194.3223438

Trying to understand why that is.

**Comment by kennethreitz** [comment]
@Tafkas anything i can do to help?

**Comment by kennethreitz** [comment]
Related #60

**Comment by kennethreitz** [comment]
Related #59

**Comment by kennethreitz** [comment]
pulling in @dgouldin to see if he knows why the tests are failing in this strange way

**Comment by Tafkas** [comment]
The weirdest part is, that if I run the test suite multiple times it would succeed in some cases. I can't reproduce the error deterministically.

**Comment by emattiza** [comment]
How about an is_close per PEP 485 on the __eq__ of MayaInterval? Perhaps an all(is_close(starts, ends)). Is this a floating point problem with the seconds representation? What's an acceptable difference look like?

**Comment by kennethreitz** [comment]
@emattiza that sounds good to me!

**Comment by kennethreitz** [comment]
fixed it!

**Pull request merged**
